CodeOutJudge/CodeOutJudge/urls.py
from django.contrib import admin
from django.urls import path , include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('Problems.urls')),
    path('profiles/' , include('Profiles.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CodeOutJudge/Problems/urls.py
from django.urls import path
from . import views

app_name = 'Problems'
urlpatterns = [
    path('' , views.index , name = 'index'),
    path('login/' , views.log_in , name = 'login'),
    path('signup/' , views.sign_up , name = 'signup'),
    path('signup_request/' , views.sign_up_request , name = 'sign_up_request'),
    path('additional_info/' , views.additional_info , name = 'additional_info'),
    path('logout/' , views.log_out ,  name = 'logout'),
    path('problems/' , views.list_problems , name = "problems"),
    path('problems/<int:problem_id>/' , views.view_problem , name = 'view_problem'),
    path('<int:problem_id>/run/' , views.run_code , name = "run_code"),
    path('blogs/<int:blog_id>/' , views.like_incrementer , name = 'like_incrementer')
]

CodeOutJudge/Profiles/urls.py
from django.urls import path
from . import views

app_name = 'Profiles'
urlpatterns = [
    path('view_profile/<int:profile_id>' , views.view_profile , name = 'view_profile'),
    path('find_profile/' , views.find_profile , name = 'find_profile'),
    path('not_found/' , views.display_profile_not_found , name = 'profile_not_found'),
    path('<int:profile_id>/submissions' , views.submissions_display , name = 'submissions'),
    path('<int:profile_id>/blogs/' , views.user_blogs_list , name = 'blog_list'),
    path('<int:blog_id>/display_blog' , views.display_blog , name = 'blog_display'),
    path('<int:profile_id>/user_problems' , views.user_problem , name = 'user_problem'),
    path('blog_form/' , views.blog_form_render , name = 'blog_form'),
    path('save_form/' , views.get_blog , name = 'save_blog'),
    path('comment/<int:blog_id>' , views.add_comment , name = 'add_comment'),
]

CodeOutJudge/Profiles/models.py
from django.db import models

CodeOutJudge/Profiles/forms.py
from django.db import models
from django import forms
from Problems.models import Blogs , Comments

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blogs
        fields = [
            'title',
            'content',
        ]

        widgets = {
            'title' : forms.TextInput(
                attrs = {
                    'class' : 'form-control'
                }
            ),
            'content' : forms.Textarea(
                attrs = {
                    'class' : 'form-control'
                }
            ),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments

        labels = {
            'content' : 'Write Comment'
        }
        fields = [
            'content'
        ]

        widgets = {
            'content' : forms.Textarea(
                attrs = {
                    'class' : 'form-control'
                }
            )
        }

CodeOutJudge/Profiles/views.py
from django.shortcuts import render , redirect
from Problems.models import Profile , Problem , Blogs , Submission
from django.http import Http404 , HttpResponse
from django.contrib.auth.models import User
from .forms import BlogForm , CommentForm
from django.forms import ModelForm
from django.utils import timezone

# Create your views here.
def view_profile(request , profile_id):
    try:
        profile = Profile.objects.get(id = profile_id)
        problem_count = profile.problem_set.count()

        return render(request , 'profiles/display_profile.html' , {
            'profile' : profile,
            'problem_count' : problem_count,
            'profile': profile,
        })

    except:
        raise Http404('Profile Not Found')

def find_profile(request):
    if request.method == 'POST':
        try:
            user = User.objects.get(username = request.POST.get('search'))
            profile = Profile.objects.get(user = user)

            return redirect('/profiles/view_profile/' + str(profile.id))
        
        except:
            return redirect('/profiles/not_found')
        
    else:
        raise Http404('Something went Wrong')

def display_profile_not_found(request):
    return render(request , 'profiles/profile_not_found.html')


def submissions_display(request , profile_id):
    profile = Profile.objects.get(id = profile_id)
    submissions = profile.submission_set.filter(user = profile).order_by('-creation_time')

    return render(request , 'problems/submissions.html' , {
        'codes' : submissions,
        'profile' : profile,
    })


def user_blogs_list(request , profile_id):
    profile = Profile.objects.get(id = profile_id)
    blogs = profile.creator.all().order_by('-created_time')

    return render(request , 'profiles/blog_list.html' , {
        'blogs' : blogs,
        'profile' : profile,
    })

def display_blog(request , blog_id):
    try:
        profile = Profile.objects.get(user = request.user)
        blog = Blogs.objects.get(id = blog_id)
        comments = blog.comments_set.all().order_by('-created_time')
        comment = CommentForm()

        return render(request , 'profiles/blog_display.html' , {
            'blog' : blog,
            'comments' : comments,
            'form' : comment,
            'profile' : profile,
        })
    except:
        raise Http404('Something went Wrong!!!!')

def user_problem(request , profile_id):
    try:
        profile = Profile.objects.get(id = profile_id)
        problems = profile.problem_set.all()
        attempted_problems = Profile.objects.get(user = request.user).problem_set.all()

        return render(request, 'profiles/user_solved_problems.html' , {
            'problems' : problems,
            'attempted_problems' : attempted_problems,
            'profile' : profile,
        })
    except:
        raise Http404('Something Went Wrong')


def blog_form_render(request):
    profile = Profile.objects.get(user = request.user)
    form = BlogForm()
    return render(request , 'profiles/blog_form.html' , {
        'form' : form,
        'profile': profile
    })


def get_blog(request):
    profile = Profile.objects.get(user = request.user)
    if request.method == 'POST':    
        blog_form = BlogForm(request.POST)

        if blog_form.is_valid():
            blog = blog_form.save(commit = False)
            profile = Profile.objects.get(user = request.user)
            blog.user = profile
            blog.created_time = timezone.now()
            blog.save()
            return redirect('/')
    
    else:
        blog = BlogForm()
    
    return render(request , 'profiles/blog_form.html' , {
        'profile' : profile
    })


def add_comment(request , blog_id):
    if request.method == 'POST':
        comment_instance = CommentForm(request.POST)

        if comment_instance.is_valid():
            profile = Profile.objects.get(user = request.user)
            blog = Blogs.objects.get(id = blog_id)

            comment = comment_instance.save(commit = False)
            comment.user = profile
            comment.blog = blog
            comment.created_time = timezone.now()
            comment.save()
        
        
    return redirect('/profiles/' + str(blog_id) + '/display_blog')
    
        

CodeOutJudge/CodeOutJudge/templates/profiles/additional_info.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'profiles_styles/login.css' %}">
    <title>CodeOut</title>
  </head>
  <body>
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <form method="POST" action="{% url 'Problems:additional_info' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="bio">bio : </label>
                        <input type="text" name = "bio"  class="form-control"><br />
                    </div>
                    <div class="form-group">
                        <label for="birth_date">BirthDay : </label>
                        <input type="date" name = "birth_date" class="form-control"><br />
                    </div>
                    <div class="form-group">
                        <label for="location">Location : </label>
                        <input type="text" name="location" class="form-control"><br />
                    </div>

                    <div class="form-group">
                        <label for="image_url">Profile Pic</label>
                        <input type="file" name="image_url" class="form-control"><br />
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>
    

CodeOutJudge/CodeOutJudge/templates/profiles/blog_display.html
{% extends 'basic_templates/navbar.html' %}

{% block content %}
    <div class="card">
        <img src="https://source.unsplash.com/1600x450/?programming,coding" class="card-img-top" alt="...">
        <div class="card-body">
            <h1 class="card-title">{{ blog.title }}</h1>
            <p class="card-text">{{ blog.content }}.</p>
            <button id="like" onClick='updateLikes({{ blog.id }})'><img src="/media/utilities/like.png" alt="img" width="50px" height="50px"></button>  <span id="like-count{{blog.id}}">{{ blog.like_count }}</span>            <footer class="blockquote-footer">Author : <cite title="Source Title">{{ blog.user.user.username }}</cite></footer>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3>Comments</h3>
        </div>
        <form action="{% url 'Profiles:add_comment' blog.id %}" method="POST">
        {% csrf_token %}
            {{ form }}

            <input type="submit" value="comment" class="btn btn-light float-right" style="margin: 1% 0;">
        </form>
        <ul class="list-group list-group-flush">
            {% for comment in comments %}
                <li class="list-group-item">
                    <strong class="text-danger">
                        {% if comment.user.profile_pic %}
                            <img src="{{ comment.user.profile_pic.url }}" width="40px" height="40px" style="border-radius: 50%;">
                        {% endif %}
                        {% if not comment.user.profile_pic %}
                            <img src="/media/profile_pics/default.jpeg" width="50px" height="50px" style="border-radius: 50%;">
                        {% endif %}
        
                        {{ comment.user.user.username }}
                    </strong>
                    <p class="blockquote-footer">{{ comment.created_time }}</p>
                    <p>{{ comment.content }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>

    <script>
        updateLikes = (blog_id) => {
            fetch('http://127.0.0.1:8000/blogs/' + blog_id)
            .then((response) => {
                return response.json();
            })
            .then((data) => {
                console.log(data);
                if(data === 'You have already liked this block') {
                    alert(data)
                }
                else
                    document.getElementById('like-count' + blog_id).innerHTML = data
            }) 
            .catch ((err) => { console.log(err) });
        }
    </script>

{% endblock %}

CodeOutJudge/CodeOutJudge/templates/profiles/blog_form.html
{% extends 'basic_templates/navbar.html' %}

{% block content %}
    <div class="container" style="margin-top: 3%;">
        <form action="{% url 'Profiles:save_blog' %}" method="POST">
        {% csrf_token %}
            {{ form }}
            <input type="submit" value="save" class="btn btn-primary" style="margin: 5% 0;">
        </form>
    </div>
{% endblock %}

CodeOutJudge/CodeOutJudge/templates/profiles/blog_list.html
{% extends 'basic_templates/navbar.html' %}

{% block content %}
    <table class="table table-hover">
        <thead>
            <tr>
            <th scope="col">Blog Title</th>
            <th scope="col">Likes</th>
            </tr>
        </thead>
        <tbody>
            {% for blog in blogs %}
                <tr>
                    <td><a href="{% url 'Profiles:blog_display' blog.id %}">{{ blog.title }}</a></td>
                    <td>{{ blog.like_count }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

CodeOutJudge/CodeOutJudge/templates/profiles/display_profile.html
{% extends 'basic_templates/navbar.html' %}

{% block content %}

    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="/media/utilities/profile_carousel1.jpeg" class="d-block w-100" alt="..." width="100%" height="400px">
          <div class="carousel-caption d-none d-md-block">
            <a href="{% url 'Profiles:submissions' profile.id %}" class="btn btn-info" style="margin: 3%;">Submissions</a>
            <p>Browse the submissions of the {{ profile.user.username }}</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="/media/utilities/profile_carousel2.jpeg" class="d-block w-100" alt="..." width="100%" height="400px">
          <div class="carousel-caption d-none d-md-block">
            <a href="{% url 'Profiles:user_problem' profile.id %}" class="btn btn-info" style="margin: 3%;">Problems</a>
            <p>Browse the problems solved by {{ profile.user.username }}</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="/media/utilities/profile_carousel3.jpeg" class="d-block w-100" alt="..." width="100%" height="400px">
          <div class="carousel-caption d-none d-md-block">
            <a href="{% url 'Profiles:blog_list' profile.id %}" class="btn btn-info" style="margin: 3%;">Blogs</a>
            <p>Visit the blogs created by {{ profile.user.username }}</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

    <div class="container" style="margin: 5%; text-align: left;">
        <div class="row">
          <div class="col">
            <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><h2>{{ profile.user.username }}</h2>
                  <h6 class="card-subtitle mb-2 text-muted">{{ profile.bio }}</h6>
                  <p class="card-text">
                      <ul class="list-group list-group-flush">
                        <li class="list-group-item">Place : {{ profile.location }}</li>
                        <li class="list-group-item">Birth-date : {{ profile.birth_date }}</li>
                        <li class="list-group-item">Problems solved : <span class="badge badge-primary">{{ problem_count }}</span></li>
                      </ul>
                  </p>
                </div>
            </div>
          </div>
          <div class="col-md-auto">
            <div class="card" style="border: none;">
              {% if profile.profile_pic %}
                <img src="{{ profile.profile_pic.url }}" style="width: 250px; height: 250px; border-radius:50%;">
              {% endif %}
              {% if not profile.profile_pic %}
                <img src="/media/profile_pics/default.jpeg" style="width: 250px; height: 250px; border-radius:50%;">
              {% endif %}
            </div>
          </div>
        </div>
    </div>

{% endblock %}

CodeOutJudge/CodeOutJudge/templates/profiles/index.html
{% extends 'basic_templates/navbar.html' %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'profiles_styles/index.css' %}">
    <div class="container my-4">
      <div class="row mb-2">
        <div class="col-lg">
          {% for blog in blogs %}          
            <div class="card">
                <div class="card-header" style="padding: 0%;">
                    <a href="{% url 'Profiles:blog_display' blog.id %}" class="list-group-item list-group-item-action"  style="background:rgb(220,220,220)">{{ blog.title }}</a>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ blog.profile.user.username }}</h5>
                    <p class="card-text">{{ blog.content }}</p>
                    <button id="like" onClick='updateLikes({{ blog.id }})'><img src="/media/utilities/like.png" alt="img" width="50px" height="50px"></button>  <span id="like-count{{blog.id}}">{{ blog.like_count }}</span>
                </div>
            </div>
          {% endfor %}
        </div>
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                {% if profile.profile_pic %}
                <img src="{{ profile.profile_pic.url }}" class="card-img-top circular--landscape" style="margin: 2.5rem;" alt="...">
                {% endif %}

                {% if not profile.profile_pic %}
                <img src="/media/profile_pics/default.jpeg" class="card-img-top circular--landscape" style="margin: 2.5rem;" alt="image can't be loaded">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ profile.user.username }}</h5>
                    <p class="card-text">Problems solved : {{ problem_count }}</p>
                    <a href="{% url 'Profiles:view_profile' profile.id %}" class="btn btn-primary">Display Profile</a>
                </div>
            </div>
        </div>
      </div>
    </div>

    <script>
      updateLikes = (blog_id) => {
          fetch('http://127.0.0.1:8000/blogs/' + blog_id)
          .then((response) => {
              return response.json();
          })
          .then((data) => {
              console.log(data);
              if(data === 'You have already liked this block') {
                  alert(data)
              }
              else
                  document.getElementById('like-count' + blog_id).innerHTML = data
          }) 
          .catch ((err) => { console.log(err) });
      }
  </script>
{% endblock %}

CodeOutJudge/CodeOutJudge/templates/profiles/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'profiles_styles/login.css' %}">
    <title>CodeOut</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT7dd0u49G6FuV_-tBcJu6vVQE4YR_6j998-aqHaJFDe2am0rah&usqp=CAU"
            width="30"
            height="30"
            class="d-inline-block align-top"
            alt=""
            loading="lazy"/>CodeOut</a>
        </span>
    </nav>
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <form method="POST" action="{% url 'Problems:login' %}">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="username">UserName</label>
                        <input type="text" name = "username" class="form-control"><br />
                    </div>
                    <div class="form-group">
                        <label for="password">PassWord</label>
                        <input type="password" name="password" class="form-control"><br />
                    </div>
                    {% if error_message %}
                        <p id="error_message">*{{ error_message }}</p>
                    {% endif %}

                    {% if next %}
                        <h6>You can't display the text</h6>
                    {% endif %}
                    <span id="submit">
                        <button type="submit" class="btn btn-primary">Login</button><br />
                    </span>
                </form>

                <a href="{% url 'Problems:sign_up_request' %}">Sign Up</a>

            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

CodeOutJudge/CodeOutJudge/templates/profiles/profile_not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Profile Not found</h1>
</body>
</html>

CodeOutJudge/CodeOutJudge/templates/profiles/sign_up.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'profiles_styles/login.css' %}">
    <title>CodeOut</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT7dd0u49G6FuV_-tBcJu6vVQE4YR_6j998-aqHaJFDe2am0rah&usqp=CAU"
            width="30"
            height="30"
            class="d-inline-block align-top"
            alt=""
            loading="lazy"/>CodeOut</a>
        </span>
    </nav>
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <form method="POST" action="{% url 'Problems:signup' %}">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="username">UserName </label>
                        <input type="text" name = "username" class="form-control"><br />
                    </div>
                    <div class="form-group">
                        <label for="password">PassWord</label>
                        <input type="password" name="password" class="form-control"><br />
                    </div>
                    {% if error_message %}
                        <p id="error_message">*{{ error_message }}</p>
                    {% endif %}
                    <span id="submit">
                        <button type="submit" class="btn btn-primary">Sign Up</button><br />
                    </span>

                    <a href="{% url 'Problems:login' %}">Login</a>
                </form>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

CodeOutJudge/CodeOutJudge/templates/profiles/user_solved_problems.html
{% extends 'basic_templates/navbar.html' %}

{% block content %}
    <table class="table table-hover">
        <thead>
            <tr>
            <th scope="col" style="width: 75%;">Problem Name</th>
            <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            {% for problem in problems %}
                <tr>
                    <td><a href="{% url 'Problems:view_problem' problem.id %}">{{ problem.problem_name }}</a></td>
                    <td>
                        {% if problem in attempted_problems %}
                            Attempted
                        {% endif %}
                        {% if problem not in attempted_problems %}
                            Not Attempted
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}