CodeOutJudge/CodeOutJudge/urls.py
from django.contrib import admin
from django.urls import path , include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('Problems.urls')),
    path('profiles/' , include('Profiles.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CodeOutJudge/Problems/urls.py
from django.urls import path
from . import views

app_name = 'Problems'
urlpatterns = [
    path('' , views.index , name = 'index'),
    path('login/' , views.log_in , name = 'login'),
    path('signup/' , views.sign_up , name = 'signup'),
    path('signup_request/' , views.sign_up_request , name = 'sign_up_request'),
    path('additional_info/' , views.additional_info , name = 'additional_info'),
    path('logout/' , views.log_out ,  name = 'logout'),
    path('problems/' , views.list_problems , name = "problems"),
    path('problems/<int:problem_id>/' , views.view_problem , name = 'view_problem'),
    path('<int:problem_id>/run/' , views.run_code , name = "run_code"),
    path('blogs/<int:blog_id>/' , views.like_incrementer , name = 'like_incrementer')
]

CodeOutJudge/Profiles/urls.py
from django.urls import path
from . import views

app_name = 'Profiles'
urlpatterns = [
    path('view_profile/<int:profile_id>' , views.view_profile , name = 'view_profile'),
    path('find_profile/' , views.find_profile , name = 'find_profile'),
    path('not_found/' , views.display_profile_not_found , name = 'profile_not_found'),
    path('<int:profile_id>/submissions' , views.submissions_display , name = 'submissions'),
    path('<int:profile_id>/blogs/' , views.user_blogs_list , name = 'blog_list'),
    path('<int:blog_id>/display_blog' , views.display_blog , name = 'blog_display'),
    path('<int:profile_id>/user_problems' , views.user_problem , name = 'user_problem'),
    path('blog_form/' , views.blog_form_render , name = 'blog_form'),
    path('save_form/' , views.get_blog , name = 'save_blog'),
    path('comment/<int:blog_id>' , views.add_comment , name = 'add_comment'),
]

CodeOutJudge/CodeOutJudge/templates/basic_templates/navbar.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'Problems:index' %}"
          ><img
            src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT7dd0u49G6FuV_-tBcJu6vVQE4YR_6j998-aqHaJFDe2am0rah&usqp=CAU"
            width="30"
            height="30"
            class="d-inline-block align-top"
            alt=""
            loading="lazy"
          />CodeOut</a
        >
  
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'Problems:problems' %}"
                >Problems<span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Profiles:blog_form' %}">Create Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/admin">Admin Area</a>
            </li>
           
          </ul>

          <a class= "nav-link my-2 my-lg-0" href="{% url 'Profiles:view_profile' profile.id %}"
            ><img src={{ profile.profile_pic.url }} style="width: 40px; height: 40px; border-radius:50%;"><span class="sr-only">(current)</span></a
          >
          <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'Profiles:find_profile' %}">
            {% csrf_token %}
            <input
              class="form-control mr-sm-2"
              type="search"
              placeholder="Search any user"
              aria-label="Search"
              name="search"
            />
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
              Search
            </button>
          </form>
          <a href="{% url 'Problems:logout' %}" class="btn btn-outline-success my-2 my-sm-0">Log Out</a>
        </div>
    
    </nav>

    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </body>
</html>